### ISSUE TITLE
No search results give blank page

### ISSUE THREAD

**Issue by KhubiThakkar** [DhyeyShah45/fun-space#4]
If you search for a term and there are no results, the page goes blank without navbar or anything
![image](https://github.com/DhyeyShah45/fun-space/assets/29814343/a59aa790-115e-4637-9fa5-002f33e7baea)

**Comment by DhyeyShah45** [comment]
@KhubiThakkar I have tried to solve the issues. I have pushed them in the issueSolver branch. We'll discuss it later about the merge request.

**Comment by KhubiThakkar** [comment]
@DhyeyShah45 I have reviewed and solved the other issues in the merge request.
